name: releases.sheetize.com
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@v4
      with:
          repository: smallize/sheetize
          ref: "releases.sheetize.com"
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
          submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.135.0'
          extended: true
    - name: Build 
      run: hugo --config "configs/releases.sheetize.com.toml","configs/common.sheetize.com.toml" -b "${{ steps.base-url.outputs.url }}" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Deploy
      run: hugo deploy --config "configs/releases.sheetize.com.toml" --maxDeletes=-1 --target "${{ github.event.inputs.environment }}" --invalidateCDN --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_2 }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_2 }}
