name: www.sheetize.com
on:
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment'
          type: environment
          default: production
          required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@v4
      with:
          repository: smallize/sheetize
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
          submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.135.0'
          extended: true
    - name: Determine Base URL
      id: base-url
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "::set-output name=url::https://wwww.sheetize.com"
        else
          echo "::set-output name=url::https://qa.sheetize.com"
        fi     
    - name: Build 
      run: hugo --config "configs/www.sheetize.com.toml","configs/common.sheetize.com.toml" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Deploy
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
         hugo deploy --config "configs/www.sheetize.com.toml" --maxDeletes=0 --target "production" --invalidateCDN --force
        else
          hugo deploy --config "configs/qa.sheetize.com.toml" --maxDeletes=0 --target "staging" --invalidateCDN --force
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
